name: Fuzz APWorld
on:
  push:
    branches: [anodyne]
  pull_request:
    branches: [anodyne]


jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: Eijebong/ap-actions/fuzz@main
        with:
          apworld-path: worlds/anodyne
          ap-version: '0.6.3'
          python-version: '3.12'
